# Development compose
version: "3.8"
services:
  frontend:
    image: node:18
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run dev"

  backend:
    image: golang:1.19.3
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/usr/src/backend
    working_dir: /usr/src/backend
    command: bash -c "go install && go run main.go"

  db:
    image: postgres:15.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - '5432:5432'


  