# Development compose
version: "3.8"
services:
  frontend:
    build: frontend.Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app
  backend:
    build: backend.Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/app
  db:
    image: postgres:15.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data


  