# Development compose
version: "3.8"
services:
  frontend:
    image: node:18
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    environment:
      NODE_ENV: "development"
    command: bash -c "npm install && npm run dev"

  backend:
    image: golang:1.19.3
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/usr/src/backend
    working_dir: /usr/src/backend
    command: bash -c "go install && go run main.go"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_DB: "canyes"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"

  db:
    image: postgres:15.0
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw